name: docker-ci

on: push

jobs:
  docker-front:
    needs: frontend-tests-workflow
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push frontend
        uses: docker/build-push-action@v4
        with:
          push: true
          context: "{{defaultContext}}:frontend"
          file: Dockerfile.prod
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/wildrent-frontend:latest
      - name: Build and push backend
        uses: docker/build-push-action@v4
        with:
          push: true
          context: "{{defaultContext}}:backend"
          file: Dockerfile.prod
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/wildrent-backend:latest
  