name: frontend-tests-workflow

on: pull_request

jobs:
  test-client:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Goto frontend and run tests
        run: cd frontend && npm i && npm test
  test-e2e: 
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: run e2e tests
        run:  docker compose -f docker-compose.e2e.yml up --build --exit-code-from e2e